// <auto-generated />
namespace cgsmvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Anno : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Anno));
        
        string IMigrationMetadata.Id
        {
            get { return "201503040238424_Anno"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
